### ISSUE TITLE
l4d2_jockey_jumpcap_patch.sp and l4d2_jockeyed_charger_fix.sp have double hook ability_leap

### ISSUE THREAD

**Issue by Electr0** [Attano/L4D2-Competitive-Framework#15]
this because you hook void OnEntityCreated by DHookAddEntityListener but this void currently fired by sdkhooks by default. this cause double fire same code in callback named as OnEntityCreated.

for fix just remove line DHookAddEntityListener(ListenType_Created, OnEntityCreated); because it is an unnecessary since sdkhooks built in sourcemod since 1.5.x.

**Comment by Attano** [comment]
Thanks. Feel free to make a pull request if you have a fixed copy.
